<?php

/**
 * @file
 * Module file for block_example.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityInterface;


 function clean_filenames_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityType()->id() == 'node') {
    $entity->getTitle('The new Title');
    $entity_data = $entity->getTypedData();
    dpm($entity_data);
    //CAUTION : Do not save here, because it's automatic.
  }
}

/**
 * @} End of "defgroup block_example".
 */
